name:                Mutation
version:             0.1.0.0
github:              
license:             
author:              "Jeff Chen"
maintainer:          "yutingc@chalmers.se"
copyright:           "2018 Jeff Chen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/HaskellSandbox#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  HaskellSandbox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellSandbox
    - quickspec >= 2
    - twee-lib >= 2.1.2

tests:
  HaskellSandbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellSandbox
